// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jxlwqq/todo/api/proto/v1"
	"github.com/jxlwqq/todo/internal/todo"
	"github.com/jxlwqq/todo/pkg/dbcontext"
)

// Injectors from wire.go:

func InitTodoService(DSN string) (v1.TodoServiceServer, error) {
	db := dbcontext.NewDB(DSN)
	repository := todo.NewRepository(db)
	todoServiceServer := todo.NewService(repository)
	return todoServiceServer, nil
}
