// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jxlwqq/todo/api/todo/v1"
	"github.com/jxlwqq/todo/internal/todo"
	"github.com/jxlwqq/todo/pkg/dbcontext"
)

// Injectors from wire.go:

func InitTodoServer(DSN string) (v1.TodoServer, error) {
	db := dbcontext.NewDB(DSN)
	repository := todo.NewRepository(db)
	todoServer := todo.NewServer(repository)
	return todoServer, nil
}
